### ISSUE TITLE
Question: how to caption verbal flubs/misstakes in speaking

### ISSUE THREAD

**Issue by Blaisorblade** [lkuper/icfp2020-captions#2]
I haven't started reviewing my captions, but I'll probably run into this question, and so might others.
Should captions reflect verbal flubs, or what we meant to say? I realize the question is not great in this form, but maybe you have useful advice anyway.

**Comment by Blaisorblade** [comment]
And I realize talks were recorded, but I will admit I did not manage to edit the recording to perfection.

**Comment by lkuper** [comment]
Our approach was to try to capture what the speaker said, although we didn't faithfully include every "um" or "uh".  Use your best judgment!
